### ISSUE TITLE
Maintaining footnotes

### ISSUE THREAD

**Issue by Ryuno-Ki** [soapdog/firefoxos-quick-guide#29]
Hello,

while reading through your guide, I noticed redundant footnotes.

Now looking at the source code, I see, that you always added the link directly. May I ask, why you didn't use [ID](http://daringfireball.net/projects/markdown/syntax#link)s according to the syntax specs? That would reduce the redundancy a lot.

One could think about using endnotes here (e.g. at the end of each chapter), too.

**Comment by soapdog** [comment]
I don't want to use endnotes because this is a pick and go book. Some people will just pick it up and look at a couple pages at a time. The endnotes make them jump to the end of the chapter and not all readers do the jump back correctly.

Personally, I dislike endnotes but this is just personal taste. I will look into redundant links but I am not worried about them. IMHO I don't really care if I have a link in a page and then some pages afterward I have the same link again.

**Comment by Ryuno-Ki** [comment]
Ah, okay. Well, I think, you have to change more things than. Currently, a reader has to read it in a linear fashion. Which is okay.

Can you ask Leanpub to move the footnotes to the bottom of the page? Right now, they're appended to the end of a site's page, but not necessary at the bottom :-/
