### ISSUE TITLE
Using string interpolation?

### ISSUE THREAD

**Issue by Ryuno-Ki** [soapdog/firefoxos-quick-guide#32]
Hello,

I'm wondering, wether the usage of [sprintf](http://www.diveintojavascript.com/projects/javascript-sprintf) may be to confusing for beginners? For me, I'm familar with the concept (+ it is easier to translate apps this way ;-)).

It's up to you. I can edit the code snippets, if you like.

**Comment by soapdog** [comment]
I am trying not to use stuff outside of vanilla javascript right now. I chose to do that because I don't want the rookie developers thinking that they need this or that project to develop for Firefox OS.

I plan to add some stuff related to tools but I am planning to pick tools with more features than just the sprintf implementation but that is a good candidate to a blog/wiki post listing interesting projects to be linked in the book.

**Comment by Ryuno-Ki** [comment]
You wrote in the guide, that you'd modify it with respect to readers' feedback. This was one of them :-)
